---
# =============================================================================
# Deploy Playbook
# Run this as the regular user to install packages and configure the system
# Usage: ansible-playbook -i "IP," -u barnaby playbook.yml
# =============================================================================

- hosts: all
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: 01-core-packages
    - role: 02-shell
    - role: 03-motd
    - role: 06-firewall
      vars:
        firewall_allowed_tcp_ports:
          - "22"

  post_tasks:
    - name: Reboot the machine
      become: true
      ansible.builtin.reboot:
        reboot_timeout: 300
