---
- name: Wait for unattended-upgrades to finish
  become: true
  ansible.builtin.command: fuser /var/lib/dpkg/lock-frontend
  register: dpkg_lock
  until: dpkg_lock.rc != 0
  retries: 60
  delay: 5
  changed_when: false
  failed_when: false

- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade all packages
  become: true
  ansible.builtin.apt:
    upgrade: dist
